// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package kernelcapture

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type launcherIdentityArdurLauncherExecState struct {
	_           structs.HostLayout
	Inode       uint64
	MountId     uint64
	DeviceMajor uint32
	DeviceMinor uint32
	LinkCount   uint32
	Pad         uint32
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	launcherIdentityMapLauncherExecState        = "launcher_exec_state"
	launcherIdentityProgObserveLauncherIdentity = "observe_launcher_identity"
)

// loadLauncherIdentity returns the embedded CollectionSpec for launcherIdentity.
func loadLauncherIdentity() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_LauncherIdentityBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load launcherIdentity: %w", err)
	}

	return spec, err
}

// loadLauncherIdentityObjects loads launcherIdentity and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*launcherIdentityObjects
//	*launcherIdentityPrograms
//	*launcherIdentityMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadLauncherIdentityObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadLauncherIdentity()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// launcherIdentitySpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type launcherIdentitySpecs struct {
	launcherIdentityProgramSpecs
	launcherIdentityMapSpecs
	launcherIdentityVariableSpecs
}

// launcherIdentityProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type launcherIdentityProgramSpecs struct {
	ObserveLauncherIdentity *ebpf.ProgramSpec `ebpf:"observe_launcher_identity"`
}

// launcherIdentityMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type launcherIdentityMapSpecs struct {
	LauncherExecState *ebpf.MapSpec `ebpf:"launcher_exec_state"`
}

// launcherIdentityVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type launcherIdentityVariableSpecs struct {
}

// launcherIdentityObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadLauncherIdentityObjects or ebpf.CollectionSpec.LoadAndAssign.
type launcherIdentityObjects struct {
	launcherIdentityPrograms
	launcherIdentityMaps
	launcherIdentityVariables
}

func (o *launcherIdentityObjects) Close() error {
	return _LauncherIdentityClose(
		&o.launcherIdentityPrograms,
		&o.launcherIdentityMaps,
	)
}

// launcherIdentityMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadLauncherIdentityObjects or ebpf.CollectionSpec.LoadAndAssign.
type launcherIdentityMaps struct {
	LauncherExecState *ebpf.Map `ebpf:"launcher_exec_state"`
}

func (m *launcherIdentityMaps) Close() error {
	return _LauncherIdentityClose(
		m.LauncherExecState,
	)
}

// launcherIdentityVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadLauncherIdentityObjects or ebpf.CollectionSpec.LoadAndAssign.
type launcherIdentityVariables struct {
}

// launcherIdentityPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadLauncherIdentityObjects or ebpf.CollectionSpec.LoadAndAssign.
type launcherIdentityPrograms struct {
	ObserveLauncherIdentity *ebpf.Program `ebpf:"observe_launcher_identity"`
}

func (p *launcherIdentityPrograms) Close() error {
	return _LauncherIdentityClose(
		p.ObserveLauncherIdentity,
	)
}

func _LauncherIdentityClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed launcheridentity_bpfel.o
var _LauncherIdentityBytes []byte
