// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package kernelcapture

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type processExecArdurCommKey struct {
	_    structs.HostLayout
	Comm [16]int8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	processExecMapAllowedCgroups          = "allowed_cgroups"
	processExecMapEvents                  = "events"
	processExecMapFilterControl           = "filter_control"
	processExecMapLifecycleEventsDropped  = "lifecycle_events_dropped"
	processExecMapRecognitionComms        = "recognition_comms"
	processExecMapRecognitionControl      = "recognition_control"
	processExecProgHandleSchedProcessExec = "handle_sched_process_exec"
	processExecProgHandleSchedProcessExit = "handle_sched_process_exit"
)

// loadProcessExec returns the embedded CollectionSpec for processExec.
func loadProcessExec() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProcessExecBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load processExec: %w", err)
	}

	return spec, err
}

// loadProcessExecObjects loads processExec and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*processExecObjects
//	*processExecPrograms
//	*processExecMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadProcessExecObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadProcessExec()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// processExecSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processExecSpecs struct {
	processExecProgramSpecs
	processExecMapSpecs
	processExecVariableSpecs
}

// processExecProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processExecProgramSpecs struct {
	HandleSchedProcessExec *ebpf.ProgramSpec `ebpf:"handle_sched_process_exec"`
	HandleSchedProcessExit *ebpf.ProgramSpec `ebpf:"handle_sched_process_exit"`
}

// processExecMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processExecMapSpecs struct {
	AllowedCgroups         *ebpf.MapSpec `ebpf:"allowed_cgroups"`
	Events                 *ebpf.MapSpec `ebpf:"events"`
	FilterControl          *ebpf.MapSpec `ebpf:"filter_control"`
	LifecycleEventsDropped *ebpf.MapSpec `ebpf:"lifecycle_events_dropped"`
	RecognitionComms       *ebpf.MapSpec `ebpf:"recognition_comms"`
	RecognitionControl     *ebpf.MapSpec `ebpf:"recognition_control"`
}

// processExecVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processExecVariableSpecs struct {
}

// processExecObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadProcessExecObjects or ebpf.CollectionSpec.LoadAndAssign.
type processExecObjects struct {
	processExecPrograms
	processExecMaps
	processExecVariables
}

func (o *processExecObjects) Close() error {
	return _ProcessExecClose(
		&o.processExecPrograms,
		&o.processExecMaps,
	)
}

// processExecMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadProcessExecObjects or ebpf.CollectionSpec.LoadAndAssign.
type processExecMaps struct {
	AllowedCgroups         *ebpf.Map `ebpf:"allowed_cgroups"`
	Events                 *ebpf.Map `ebpf:"events"`
	FilterControl          *ebpf.Map `ebpf:"filter_control"`
	LifecycleEventsDropped *ebpf.Map `ebpf:"lifecycle_events_dropped"`
	RecognitionComms       *ebpf.Map `ebpf:"recognition_comms"`
	RecognitionControl     *ebpf.Map `ebpf:"recognition_control"`
}

func (m *processExecMaps) Close() error {
	return _ProcessExecClose(
		m.AllowedCgroups,
		m.Events,
		m.FilterControl,
		m.LifecycleEventsDropped,
		m.RecognitionComms,
		m.RecognitionControl,
	)
}

// processExecVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadProcessExecObjects or ebpf.CollectionSpec.LoadAndAssign.
type processExecVariables struct {
}

// processExecPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadProcessExecObjects or ebpf.CollectionSpec.LoadAndAssign.
type processExecPrograms struct {
	HandleSchedProcessExec *ebpf.Program `ebpf:"handle_sched_process_exec"`
	HandleSchedProcessExit *ebpf.Program `ebpf:"handle_sched_process_exit"`
}

func (p *processExecPrograms) Close() error {
	return _ProcessExecClose(
		p.HandleSchedProcessExec,
		p.HandleSchedProcessExit,
	)
}

func _ProcessExecClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed processexec_bpfel.o
var _ProcessExecBytes []byte
