// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package kernelcapture

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type processGuardArdurCgroupOpKey struct {
	_        structs.HostLayout
	CgroupId uint64
	Op       uint32
	Slot     uint32
}

type processGuardArdurCgroupOpValue struct {
	_           structs.HostLayout
	Action      uint32
	EnforceMode uint32
	Generation  uint32
}

type processGuardArdurFileAllowKey struct {
	_         structs.HostLayout
	CgroupRaw [8]uint8
	Path      [256]int8
}

type processGuardArdurFileAllowScratch struct {
	_        structs.HostLayout
	Key      processGuardArdurFileAllowKey
	PathCopy [256]int8
}

type processGuardArdurManagedKey struct {
	_         structs.HostLayout
	CgroupRaw [8]uint8
}

type processGuardArdurManagedValue struct {
	_          structs.HostLayout
	Flags      uint32
	Generation uint32
	ActiveSlot uint32
}

type processGuardArdurNetLpmKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	CgroupRaw [8]uint8
	Addr      [16]uint8
}

type processGuardArdurPathLpmKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	CgroupRaw [8]uint8
	Path      [248]int8
}

// loadProcessGuard returns the embedded CollectionSpec for processGuard.
func loadProcessGuard() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProcessGuardBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load processGuard: %w", err)
	}

	return spec, err
}

// loadProcessGuardObjects loads processGuard and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*processGuardObjects
//	*processGuardPrograms
//	*processGuardMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadProcessGuardObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadProcessGuard()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// processGuardSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processGuardSpecs struct {
	processGuardProgramSpecs
	processGuardMapSpecs
	processGuardVariableSpecs
}

// processGuardProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processGuardProgramSpecs struct {
	GuardBprmCheck     *ebpf.ProgramSpec `ebpf:"guard_bprm_check"`
	GuardFileOpen      *ebpf.ProgramSpec `ebpf:"guard_file_open"`
	GuardSocketConnect *ebpf.ProgramSpec `ebpf:"guard_socket_connect"`
}

// processGuardMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processGuardMapSpecs struct {
	CgroupFileAllow  *ebpf.MapSpec `ebpf:"cgroup_file_allow"`
	CgroupManaged    *ebpf.MapSpec `ebpf:"cgroup_managed"`
	CgroupNetAllow   *ebpf.MapSpec `ebpf:"cgroup_net_allow"`
	CgroupOpPolicy   *ebpf.MapSpec `ebpf:"cgroup_op_policy"`
	CgroupPathAllow  *ebpf.MapSpec `ebpf:"cgroup_path_allow"`
	EnforceEvents    *ebpf.MapSpec `ebpf:"enforce_events"`
	FileAllowScratch *ebpf.MapSpec `ebpf:"file_allow_scratch"`
	KillSwitch       *ebpf.MapSpec `ebpf:"kill_switch"`
	NetLpmScratch    *ebpf.MapSpec `ebpf:"net_lpm_scratch"`
	PathLpmScratch   *ebpf.MapSpec `ebpf:"path_lpm_scratch"`
}

// processGuardVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processGuardVariableSpecs struct {
}

// processGuardObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadProcessGuardObjects or ebpf.CollectionSpec.LoadAndAssign.
type processGuardObjects struct {
	processGuardPrograms
	processGuardMaps
	processGuardVariables
}

func (o *processGuardObjects) Close() error {
	return _ProcessGuardClose(
		&o.processGuardPrograms,
		&o.processGuardMaps,
	)
}

// processGuardMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadProcessGuardObjects or ebpf.CollectionSpec.LoadAndAssign.
type processGuardMaps struct {
	CgroupFileAllow  *ebpf.Map `ebpf:"cgroup_file_allow"`
	CgroupManaged    *ebpf.Map `ebpf:"cgroup_managed"`
	CgroupNetAllow   *ebpf.Map `ebpf:"cgroup_net_allow"`
	CgroupOpPolicy   *ebpf.Map `ebpf:"cgroup_op_policy"`
	CgroupPathAllow  *ebpf.Map `ebpf:"cgroup_path_allow"`
	EnforceEvents    *ebpf.Map `ebpf:"enforce_events"`
	FileAllowScratch *ebpf.Map `ebpf:"file_allow_scratch"`
	KillSwitch       *ebpf.Map `ebpf:"kill_switch"`
	NetLpmScratch    *ebpf.Map `ebpf:"net_lpm_scratch"`
	PathLpmScratch   *ebpf.Map `ebpf:"path_lpm_scratch"`
}

func (m *processGuardMaps) Close() error {
	return _ProcessGuardClose(
		m.CgroupFileAllow,
		m.CgroupManaged,
		m.CgroupNetAllow,
		m.CgroupOpPolicy,
		m.CgroupPathAllow,
		m.EnforceEvents,
		m.FileAllowScratch,
		m.KillSwitch,
		m.NetLpmScratch,
		m.PathLpmScratch,
	)
}

// processGuardVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadProcessGuardObjects or ebpf.CollectionSpec.LoadAndAssign.
type processGuardVariables struct {
}

// processGuardPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadProcessGuardObjects or ebpf.CollectionSpec.LoadAndAssign.
type processGuardPrograms struct {
	GuardBprmCheck     *ebpf.Program `ebpf:"guard_bprm_check"`
	GuardFileOpen      *ebpf.Program `ebpf:"guard_file_open"`
	GuardSocketConnect *ebpf.Program `ebpf:"guard_socket_connect"`
}

func (p *processGuardPrograms) Close() error {
	return _ProcessGuardClose(
		p.GuardBprmCheck,
		p.GuardFileOpen,
		p.GuardSocketConnect,
	)
}

func _ProcessGuardClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed processguard_bpfel.o
var _ProcessGuardBytes []byte
