#!/usr/bin/env python3
"""Generate the machine-maintained command block in AGENTS.md.

AGENTS.md is the canonical entry point for coding agents working in this
repository. Its toolchain versions and `make` targets are derived from the
files that actually define them, not restated by hand, so that a bump to
`go/go.mod` or a new `make` target cannot silently leave AGENTS.md stale.

Sources of truth:
  * Makefile                 -> target names and their `##` help text
  * go/go.mod                -> the `go` directive (toolchain version)
  * python/pyproject.toml    -> `requires-python`
  * .pre-commit-config.yaml  -> the pinned ruff revision

Usage:
    python3 scripts/gen-agent-docs.py            # rewrite the block in place
    python3 scripts/gen-agent-docs.py --check    # fail if the block is stale

The `--check` mode mirrors site/scripts/sync_source_docs.py: it writes
nothing and returns 1 when the generated block drifts from its sources.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
AGENTS_DOC = REPO_ROOT / "AGENTS.md"

START_MARKER = "<!-- START generated-commands -->"
END_MARKER = "<!-- END generated-commands -->"

GENERATED_NOTE = (
    "<!-- Generated by scripts/gen-agent-docs.py. Do not edit by hand; run "
    "`make gen-agent-docs`. -->"
)

# Targets that are plumbing rather than something an agent should be told to
# run as a routine step.
SKIPPED_TARGETS = {"help"}


def _fail(message: str) -> None:
    print(f"gen-agent-docs failed: {message}", file=sys.stderr)


def read_go_version() -> str:
    """Return the `go` directive from go/go.mod (e.g. "1.26.5")."""
    text = (REPO_ROOT / "go" / "go.mod").read_text(encoding="utf-8")
    match = re.search(r"^go\s+(\S+)\s*$", text, re.MULTILINE)
    if not match:
        raise ValueError("no `go` directive found in go/go.mod")
    return match.group(1)


def read_requires_python() -> str:
    """Return the `requires-python` constraint from python/pyproject.toml."""
    text = (REPO_ROOT / "python" / "pyproject.toml").read_text(encoding="utf-8")
    match = re.search(
        r"""^requires-python\s*=\s*["']([^"']+)["']""", text, re.MULTILINE
    )
    if not match:
        raise ValueError("no `requires-python` found in python/pyproject.toml")
    return match.group(1)


def read_ruff_version() -> str:
    """Return the pinned ruff revision from .pre-commit-config.yaml."""
    text = (REPO_ROOT / ".pre-commit-config.yaml").read_text(encoding="utf-8")
    match = re.search(
        r"repo:\s*https://github\.com/astral-sh/ruff-pre-commit\s*\n\s*rev:\s*(\S+)",
        text,
    )
    if not match:
        raise ValueError("no ruff-pre-commit `rev` found in .pre-commit-config.yaml")
    return match.group(1)


def read_make_targets() -> list[tuple[str, str]]:
    """Return [(target, help)] for every Makefile target carrying `## ` help.

    This mirrors the `grep`/`awk` pair used by the Makefile's own `help`
    target, so the two cannot disagree about which targets are public.
    """
    text = (REPO_ROOT / "Makefile").read_text(encoding="utf-8")
    targets: list[tuple[str, str]] = []
    for line in text.splitlines():
        match = re.match(r"^([a-zA-Z_-]+):.*?## (.*)$", line)
        if not match:
            continue
        name, help_text = match.group(1), match.group(2).strip()
        if name in SKIPPED_TARGETS:
            continue
        targets.append((name, help_text))
    if not targets:
        raise ValueError("no `##`-annotated targets found in Makefile")
    return targets


def render_block() -> str:
    """Render the full generated block, markers included."""
    go_version = read_go_version()
    requires_python = read_requires_python()
    ruff_version = read_ruff_version()
    targets = read_make_targets()

    lines: list[str] = [START_MARKER, GENERATED_NOTE, ""]

    lines.append("**Toolchain versions this repository builds against:**")
    lines.append("")
    lines.append("| Toolchain | Version | Source of truth |")
    lines.append("| --- | --- | --- |")
    lines.append(f"| Go | `{go_version}` | `go/go.mod` (`go` directive) |")
    lines.append(f"| Python | `{requires_python}` | `python/pyproject.toml` |")
    lines.append(f"| ruff | `{ruff_version}` | `.pre-commit-config.yaml` |")
    lines.append("")
    lines.append(
        "CI pins the Go toolchain to the `go` directive above as a literal "
        "string in each workflow. If you bump `go/go.mod`, bump the "
        "`go-version:` in `.github/workflows/` in the same PR — nothing "
        "enforces that pairing automatically."
    )
    lines.append("")

    lines.append("**Make targets:**")
    lines.append("")
    lines.append("```bash")
    width = max(len(name) for name, _ in targets)
    for name, help_text in targets:
        lines.append(f"make {name.ljust(width)}  # {help_text}")
    lines.append("```")
    lines.append("")
    lines.append(
        "These are the convenience wrappers, and they are a **subset** of what "
        "CI runs. CI is authoritative for the full matrix."
    )
    lines.append("")
    lines.append(END_MARKER)
    return "\n".join(lines)


def splice(document: str, block: str) -> str:
    """Replace the region between the markers in `document` with `block`."""
    start = document.find(START_MARKER)
    end = document.find(END_MARKER)
    if start == -1 or end == -1:
        raise ValueError(
            f"AGENTS.md is missing the {START_MARKER} / {END_MARKER} markers"
        )
    if end < start:
        raise ValueError(f"{END_MARKER} appears before {START_MARKER} in AGENTS.md")
    return document[:start] + block + document[end + len(END_MARKER) :]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the generated block is stale instead of rewriting it",
    )
    args = parser.parse_args()

    try:
        current = AGENTS_DOC.read_text(encoding="utf-8")
        updated = splice(current, render_block())
    except (OSError, ValueError) as exc:
        _fail(str(exc))
        return 1

    if current == updated:
        print("AGENTS.md generated command block is up to date")
        return 0

    if args.check:
        _fail("AGENTS.md generated command block is stale")
        print("Run: make gen-agent-docs", file=sys.stderr)
        return 1

    AGENTS_DOC.write_text(updated, encoding="utf-8")
    print("regenerated the AGENTS.md command block")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
